export const themeDisplayNames: Record<string, string> = {
  acid: 'Acid',
  autumn: 'Autumn',
  business: 'Business',
  dim: 'Lime Noir',
  dracula: 'Dracula',
  emerald: 'Emerald',
  fantasy: 'Fantasy',
  garden: 'Garden',
  halloween: 'Halloween',
  lemonade: 'Lemonade',
  night: 'Night',
  nord: 'Nordic',
  pastel: 'Pastel',
  retro: 'Retro',
  sunset: 'Sunset',
  synthwave: 'Synthwave',
  valentine: 'Valentine',
  winter: 'Winter',
  light: 'Light',
  dark: 'Dark',
  cupcake: 'Cupcake',
  cyberpunk: 'Cyberpunk',
};

export const darkThemes = new Set([
  'business',
  'dark',
  'dim',
  'dracula',
  'halloween',
  'night',
  'synthwave',
  'sunset',
]);
